### ISSUE TITLE
 Subscription

### ISSUE THREAD

**Issue by esmaeilch81** [MrCenTury/xXx-UI#6]
سلام چطور میتونم از قابلیت Subscription که اضافه کردید استفاده کنم؟

**Comment by MrCenTury** [comment]
درود

داخل فیلد نام کاربری بنویسین بعد از بخش اطلاعات کانفیگ لینکی که بهتون داده میشه رو اگه ای پی سرور روی پورت 80 ست شده باشه بعد کلیک میاره اگه پورت دیگه ای زدین به لینک پورتو اضافه کنین

**Comment by mohamad-d** [comment]
hi
Subscription have a problem
For example, the created link is:
https://xxxxxxxxxxxxxx:2087/xui/undefinedSMD
undefined in username is not defined by me and link have error 404:
404 page not found
tnx
